### DISCUSSION TITLE
Understanding the X_resource_file parameters in the 03-wind-solar-battery example

### DISCUSSION THREAD

**Discussion by drewlwhitney** [NREL/HOPP#465] [Q&A]
Hello!

I'm a student at Colorado School of Mines. We're using HOPP to run an economic analysis comparing a system with only wind and solar to a system with wind, solar, and battery. We've never used HOPP before, so we're trying to understand the examples and documentation better.

Looking at the configuration file `examples/inputs/03-wind-solar-battery.yaml`, I want to know what the `solar_resource_file`, `wind_resource_file`, and `grid_resource_file` parameters are. I understand that the solar and wind files are related to national databases (and we need an API key to access them), but how do we know what those file names should be? I can tell the names are related to the latitude and longitude, but past that I do not know how to interface with the databases.

I could not determine what database the `grid_resource_file` is pulling from. Is it also public-access? What specifically does the grid resource entail (i.e. is that related to grid demand)?

Finally, in the `data` parameter, how can we acquire the `urdb_label`?

If there are areas in the documentation or other resources you can point me toward, I would appreciate it. Thank you!

**Comment by elenya-grant** [comment]
Thanks for this question! Below is some information that hopefully addresses your questions:

## Wind and Solar Resource Files:
The `solar_resource_file` and `wind_resource_file` are not required inputs. If these parameters are not provided in the input file, then HOPP will call the API to download the resource data files. The directory to save resource files to is specified with the `path_resource` input parameter and defaults to `/path/to/HOPP/hopp/simulation/resource_files` ([linked here](https://github.com/NREL/HOPP/tree/main/hopp/simulation/resource_files)):
```yaml
site:
    data:
        lat:
        lon:
        year: 
    path_resource: /path/to/directory/with/resource/files
```

If `wind_resource_file` or `solar_resource_file` are not provided in the input file, HOPP will look in the `path_resource` directory to see if any files exist that match the naming convention described below:
- Solar resource data is saved to the folder `path_resource/solar`. Solar resource filenames are formatted as:  
    - `{lat}_{lon}_psmv3_60_{year}.csv`
- Wind resource data is saved to the folder `path_resource/wind`. Wind resource filenames are formatted as: 
    - `{lat}_{lon}_windtoolkit_{year}_60min_{height1}_{height2}.srw` **or**
    - `{lat}_{lon}_windtoolkit_{year}_60min_{hub_height}.srw`

If the resource filepath matches an existing file, then HOPP will load resource data from that file. If not, HOPP will download resource data using the API call and save it to the resource filepath.

If HOPP was installed following the [Installing from Source](https://github.com/NREL/HOPP/blob/main/README.md#installing-from-source) instructions, then you can find the resource files you've downloaded in default folder. If HOPP was installed using `pip install HOPP`, then I'd suggest:
1. specifying `path_resource` in the input file
2. specifying the path to the `.env` file when calling `set_nrel_key_dot_env` to avoid potential errors with calling the API to download resource data (see below).

```python
from hopp.utilities.keys import set_nrel_key_dot_env

set_nrel_key_dot_env(path = '/path/to/file/.env')
```

You can check your API set-up by running Example 8 or Example 9 to see if a new resource file is downloaded.

All that is needed to interface with the resource databases is:
1. get an API key, create the .env file following the README instructions, and run the `set_nrel_key_dot_env()` function
2. all that is needed in the input file for HOPP to download resource data is:
```yaml
site:
    data:
        lat: # latitude of site within the continental U.S.
        lon: # longitude of site within the continental U.S.
        year: # use a year between 2007 and 2014
    hub_height: 80 # hub-height of wind turbine, used to determine what heights of wind resource data should be downloaded
```

Alternatively, you can make a python script to download the files manually, for example:

```python
from hopp.utilities.keys import set_nrel_key_dot_env
from hopp.simulation.technologies.resource import SolarResource, WindResource

#update the path below to the full filepath of your .env file
set_nrel_key_dot_env(path = '/fake/path/to/file/.env') 

# example location for south table mountain
lat = 39.7560
lon = -105.1914
year = 2008 # random year between 2007 and 2014

#update path_resource with the folder you want to save resource files to
path_resource = "/fake/path/to/resource/file/folder" 

# random hub-height chosen
hub_height = 90

# download wind resource data
wind_resource = WindResource(lat, lon, year, wind_turbine_hub_ht=hub_height,path_resource=path_resource)
print(f"wind resource file is saved to: {wind_resource.filename}")

# download solar resource data
solar_resource = SolarResource(lat, lon, year, path_resource=path_resource)
print(f"solar resource file is saved to: {solar_resource.filename}")
```

## Utility Rate Database (URDB) Label
The `urdb_label` is also not required in the hopp input file.
The `urdb_label` is a label specific to the [Utility Rate Database](https://openei.org/wiki/Utility_Rate_Database) that identifies a utility rate corresponding to a unique utility, rate type, sector, etc. More information is provided in the [URDB API documentation](https://openei.org/services/doc/rest/util_rates/?version=3#response-fields). This feature is only used if running REopt within HOPP (this functionality has not been finalized and is not available at the moment.)

You can acquire a `urdb_label` by searching the [Utility Rate Database](https://openei.org/wiki/Utility_Rate_Database) to find a rate that you're interested in. Click the "View" link under the "Actions" column of the table for the rate you want to use, then copy the last part of the url. 

For example, if the url is: https://apps.openei.org/USURDB/rate/view/67a6618c4a6d186c0c0c6870, then the `urdb_label` is `'67a6618c4a6d186c0c0c6870'`.

## Grid resource file
The `grid_resource_file` is also an optional input. Grid resource data is not downloaded from anywhere and the `grid_resource_file` would likely have to be made manually and should look similar to files in [this folder](https://github.com/NREL/HOPP/tree/main/hopp/simulation/resource_files/grid). There is no standard file naming convention for grid resource files in HOPP. If not input, the grid price profile defaults to the one in [dispatch_factors_ts.csv](https://github.com/NREL/HOPP/blob/main/hopp/simulation/resource_files/grid/dispatch_factors_ts.csv).

The `grid_resource_file` should contain hourly grid prices in $/MWh for 1-year. The first number should correspond to the grid electricity price starting during the first hour of the year (between 12:01am and 12:59am January 1). The grid price profile impacts the battery dispatch for some battery dispatch strategies. The battery dispatch strategies that *would* be impacted by the grid price profile are: `'simple'`, `'non_convex_LV'`,`'convex_LV'`,`'one_cycle_heuristic'`. The battery dispatch strategies that would **not** be impacted by the grid price profile are `'heuristic'` and `'load_following_heuristic'`.

Some examples on specifying the battery dispatch method are found in the:
- [Example 4 input file](https://github.com/NREL/HOPP/blob/main/examples/inputs/04-load-following-battery.yaml), this uses the `'simple'` battery dispatch method.
- [Example 7 input file](https://github.com/NREL/HOPP/blob/main/examples/inputs/07-load-following-heuristic-dispatch.yaml), this uses the `'load_following_heuristic` dispatch method
- [Example 8 input file](https://github.com/NREL/HOPP/blob/main/examples/inputs/08-distributed-wind-solar-residential.yaml) and the [Example 9 input file](https://github.com/NREL/HOPP/blob/main/examples/inputs/09-distributed-wind-solar-midsize.yaml) which both use the `'load_following_heuristic` dispatch method.

**Reply by drewlwhitney** [reply]
You're incredible. The solar and wind resource files make complete sense now, we've been able to get HOPP to download them through the database APIs by setting the longitude and latitude in the **.yaml** file. I didn't realize the URDB was a linked database HOPP could access, we'll keep that in mind. I have some follow up questions concerning the grid.

I see how the **grid resource file** works now, I think we could get by with one of the example files. I want to know if we need to supply HOPP with information about the grid-side power demand (i.e. something in MW or kW over time). I ask because if I run something like 
```
config_file = path.join("config", "without_battery.yaml")
interface = HoppInterface(config_file)
interface.simulate(project_life=20)

hybrid_plant = interface.system
total_missed_load = sum(hybrid_plant.grid.missed_load)
print(f"Total missed load (kW): {total_missed_load}")
```
with a configuration file like
**without_battery.yaml**
```
# SiteInfo
site:
  data:
    lat: 39.345795
    lon: -103.873505
    elev: 1743
    year: 2014
    tz: -7
    site_details:
      site_area_m2: 76890.27
      site_shape: "square"

  hub_height: 80.0
  solar: true
  wind: true
  wave: false

# Technologies
technologies:
  pv:
    system_capacity_kw: 2000
    dc_degradation: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  wind:
    num_turbines: 6
    turbine_rating_kw: 1500
  grid:
    interconnect_kw: 8800
    ppa_price: 0.06229
```

we get `Total missed load (kW): 0.0`, so it seems like HOPP is not simulating the grid demand. If we do need to supply this file, where is a good place to find that information? Otherwise, what parameters do we need to change/include so that we can understand how reliable our system is in terms of meeting load requirements?

Thank you so much, y'all are the best!

**Reply by elenya-grant** [reply]
Glad to hear the previous response was helpful!

The grid demand/load profile is set in the `site` section of the input file under the variable `desired_schedule`. The `desired_schedule` should be an list containing **the hourly load demand in MW** over a year (a list with 8760 entries). 

```yaml
site:
  data:
     lat: 39.345795
     lon: -103.873505
     year: 2014
     site_details:
       site_area_m2: 76890.27
       site_shape: "square"
  solar: True  
  wind: True  
  desired_schedule: [100.0, 200.0, .... 100.0] #8760 length list of load demand in MW
```

If the `desired_schedule` is *not* input, then it defaults to an empty list, and the variable `hybrid_plant.site.follow_desired_schedule` is set to False (resulting in the `hybrid_plant.grid.missed_load` value to never be updated from its default value of 0 - [see here](https://github.com/NREL/HOPP/blob/1dfebdba927f367c90007030b01cdd4c83b1f915/hopp/simulation/technologies/grid.py#L124)). If you add the `desired_schedule` to the input file, then the `hybrid_plant.grid.missed_load` should be nonzero (even without a battery).

**A quick tip**: set the grid `interconnect_kw` variable to be larger than the `desired_schedule` or you'll get a lot of printed out warnings to the terminal: 
```python
config["technologies"]["grid"]["interconnect_kw"] = max(desired_schedule)*1e3
```

- [Example 9](https://github.com/NREL/HOPP/blob/main/examples/09-distributed-midsize-example.ipynb) shows one potential method to analyze system reliability to meet load demand by seeing how missed load varies for wind and solar resource years (how robust is the design to changes in wind and solar resource data). 
- [Example 7](https://github.com/NREL/HOPP/blob/main/examples/07-load-following-heuristic-dispatch.ipynb) shows an example of setting the desired schedule in python
- [Example 8 input file](https://github.com/NREL/HOPP/blob/1dfebdba927f367c90007030b01cdd4c83b1f915/examples/inputs/08-distributed-wind-solar-residential.yaml#L18) shows another options for setting the desired schedule in the input file (the load profile is provided in a [separate file](https://github.com/NREL/HOPP/blob/main/examples/inputs/residential_load_profile_MW.yaml))
