### DISCUSSION TITLE
Financials in HOPP

### DISCUSSION THREAD

**Discussion by mmoulton1** [NREL/HOPP#486] [Q&A] [answered]
Hi,

Could someone please explain how the following are calculated in HOPP?
1. Installed cost
2. Operating costs
3. Net Present Value (NPV)
Additionally:

Is there a way to include land costs in the model?
For the `simulate()` function:

  If I set the project life to, for example, 25 years, does HOPP use 25 years of weather data, or does it only use the weather data for the single year specified in the YAML file?
 What actually changes when I run a simulation for 1 year vs. 25 years?

Thanks!

**Comment by jaredthomas68** [comment, marked as answer]
@mmoulton1, I apologize for taking so long to respond to your question. I will try to provide a reasonable answer, but feel free to follow up with further questions.

1. The installed cost for each technology is calculated as the system rating multiplied by a per MW cost. The per MW cost is calculated differently for different technologies. Some technologies (e.g. [wave](https://github.com/NREL/HOPP/blob/6149b27c795b91eb9cb8ae21102d5f5a86c75730/hopp/simulation/technologies/wave/mhk_wave_plant.py#L119)) have more detailed cost models to determine the per MW cost. Others are simply an input cost per MW. The [NREL ATB](https://atb.nrel.gov/electricity/2023/technologies) is a good reference to find cost information for different technologies. Users can specify the cost (capex is input in USD per MW and opex in input in USD per kW) for most technologies as shown in the LDES example input file (https://github.com/NREL/HOPP/blob/main/examples/inputs/11-load-following-long-duration-energy-storage.yaml). 

    The total installed cost for the hybrid system is just the sum of the installed cost for all the other technologies.

2. Operating costs for each technology are calculated based on the `cf_operating_expenses` from pysam, with adjustments if the battery was charged from the grid [for tech using the pysam financial model](https://github.com/NREL/HOPP/blob/6149b27c795b91eb9cb8ae21102d5f5a86c75730/hopp/simulation/technologies/power_source.py#L677). For [technologies using the custom financial mode](https://github.com/NREL/HOPP/blob/6149b27c795b91eb9cb8ae21102d5f5a86c75730/hopp/simulation/technologies/financial/custom_financial_model.py#L507), the operating costs are calculated as the sum of the fixed operating costs, plus the tech capacity times the tech om per capacity input, plus the tech annual energy production times the tech om per production input.

    The hybrid operating costs are calculated as follows: om_capacity using weighted average by capacities, om_fixed using sum of values, om_variable using weighted average by production of non-negative generators, om_production by weighted average by production of non-negative generators. A list of how financial parameters are determined for the hybrid system is [given in the doc strings](https://github.com/NREL/HOPP/blob/6149b27c795b91eb9cb8ae21102d5f5a86c75730/hopp/simulation/hybrid_simulation.py#L506)

4. NPV calculations in HOPP come from PySAM for individual technologies using the SingleOwner financial model. The individual technologies are then aggregated in HOPP to get the total NPV. The hybrid NPV is based on running a financial model (pysam or the custom financial model) using the aforementioned combined financial parameters to get the cash flows. The NPV is determined as the sum of the discounted cash flows 

$$ 
    NPV = \sum_{t=0}^{n}{\frac{CF_t}{(1+r)^t}}
$$

where $n$ is the number of years, $CF$ is the cash flows at each year, and $r$ is the nominal discount rate calculated from the real discount rate and the inflation rate using the Fisher equation.

5. Land cost can be included on a per rating basis as part of the cost inputs for each technology. Land cost can also be set in the pysam financial model. The custom financial model could be easily extended to include land costs separately, but this has not been done yet.

6. The production is only simulated for a single year. The one year of operation is then projected to be the same in future years. However, PV and trough solar technologies can apply degradation for each year if enabled as follows: `hi.simulate(project_life = 25, lifetime_sim = True)`. The main changes when you run for 1 vs 25 years are in the financial calculations. I believe other technologies in pysam can take yearly degradation as well, and the hopp custom financial model could be easily extended to account for degradation as well.

7. Related to all the above, cost info can be input to HOPP in the `hopp_config`file as shown:
```yaml
config:
    cost_info:
        # CapEx Costs in $/MW or $/MWh
        wind_installed_cost_mw: #wind capex in $/MW
        solar_installed_cost_mw: #PV capex in $/MW-DC
        storage_installed_cost_mw: #Battery Power Capex in $/MW
        storage_installed_cost_mwh: #Battery Energy Capex in $/MWh
        # Fixed O&M Costs in $/kW
        pv_om_per_kw:
        wind_om_per_kw:
        battery_om_per_kw:
        # Variable O&M Costs in $/MWh
        pv_om_per_mwh:
        wind_om_per_mwh:
        battery_om_per_mwh:
```
