### ISSUE TITLE
Bug report: WindPlant and WindLayout Issues

### ISSUE THREAD

**Issue by elenya-grant** [NREL/HOPP#424]
# Bugs in WindPlant and WindLayout

1.  WindPlant throws an error if certain inputs are provided in WindConfig when using FLORIS
2. num_turbines is ignored if running floris, will just assume that number of turbines reflected in the farm layout provided in floris_config (in example 5 - folks may think they're running 4 turbines but they're really only running 3)
3. WindLayout is not constrained to site layout and `min_spacing` input variable is not ever set to anything beyond the default
4. `create_grid()` and `make_grid_lines()` functions in wind_layout_tools had discrepancy in grid_angle (input as degrees in `create_grid` and passed as degrees into `make_grid_lines` - although `make_grid_lines` appears to assume its input as radians.

## How to reproduce

1. set rotor diameter in hopp_config and run with floris (example):
```
technologies:
  wind:
    rotor_diameter: 100
    model_name: floris
    timestep: [0,8760]
    floris_config: inputs/floris/gch.yaml
```

2. set num_turbines in hopp_config and run with with floris (example):
```
technologies:
  wind:
    num_turbines: 4
    model_name: floris
    timestep: [0,8760]
    floris_config: inputs/floris/gch.yaml
```
